services:
  - type: web
    name: seo-audit-webapp
    env: node
    buildCommand: |
      npm ci
      cd backend && npm ci && cd ..
      cd frontend && npm ci && npm run build && cd ..
      echo "Build completed successfully"
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
    healthCheckPath: /health