services:
  - type: web
    name: seo-audit-webapp
    env: node
    buildCommand: |
      echo "Starting build process..."
      npm ci --production=false --silent
      echo "Installing backend dependencies..."
      (cd backend && npm ci --production=false --silent)
      echo "Installing frontend dependencies..."
      (cd frontend && npm ci --production=false --silent)
      echo "Building frontend..."
      (cd frontend && CI=false npm run build)
      echo "Verifying build..."
      ls -la frontend/build/ || echo "Build directory not found"
      echo "Build process completed"
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
    healthCheckPath: /health